spring:
  application:
    name: ${THINGS_LINK_LABEL:ThingsLink}
    version: ${THINGS_LINK_VERSION:1.0.0}

server:
  port: ${THINGS_LINK_WEB_PORT:8080}


thingsLink:
  label: ${spring.application.name}
  version: ${spring.application.version}
  transport:
    mqtt:
      enable: ${TRANSPORT_MQTT_ENABLE:true}